# Name of our action
name: 'Angular ui core chromatic deployment'
# The event that will trigger the action
on:
  push:
    branches: – master
      - master-ng
      - develop
      - develop-ng
  pull_request:
    branches: – master
      - master-ng
      - develop
      - develop-ng

# What the action will do
jobs:
  chromatic-deployment:
    # The operating system it will run on
    runs-on: ubuntu-latest
    # The list of steps that the action will go through
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          buildScriptName: 'yarn build-ng-ui-core-storybook'
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
