# Name of our action
name: 'React ui core chromatic deployment'
# The event that will trigger the action
on:
  workflow_call:
  push:
    paths: ['styles/**', 'libs/react/**', 'package.json']

# What the action will do
jobs:
  chromatic-deployment:
    # The operating system it will run on
    runs-on: ubuntu-latest
    # The list of steps that the action will go through
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test-react-ui-core
      - name: Build storybook
        run: yarn build-react-ui-core-storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          storybookBuildDir: 'dist/storybook/react-ui-core'
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
